[theme]
base = "dark"
primaryColor = "#E10600"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#FFFFFF"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[browser]
gatherUsageStats = false

[server]
port = 8501
maxUploadSize = 200
maxMessageSize = 200
headless = true
enableCORS = false
enableXsrfProtection = true

[global]
# Enables or disables the Streamlit telemetry, which is usage statistics
# sent to Streamlit.
# If you care about privacy, disable this.
logTelemetry = false
dataFrameSerialization = "legacy"